### ISSUE TITLE
Module not found error, when on running main.py (python version 3.10)

### ISSUE THREAD

**Issue by d0nest** [punk-security/dnsReaper#130]
I have installed whois, still it throws this error :-

```
Traceback (most recent call last):
  File "/Users/d0nest/Stuff/Tools/dnsReaper/main.py", line 2, in <module>
    import signatures
  File "/Users/d0nest/Stuff/Tools/dnsReaper/signatures/__init__.py", line 9, in <module>
    from . import *
  File "/Users/d0nest/Stuff/Tools/dnsReaper/signatures/simplebooklet.py", line 1, in <module>
    from .templates.cname_found_but_string_in_body import cname_found_but_string_in_body
  File "/Users/d0nest/Stuff/Tools/dnsReaper/signatures/templates/__init__.py", line 9, in <module>
    from . import *
  File "/Users/d0nest/Stuff/Tools/dnsReaper/signatures/templates/cname_found_but_string_in_body.py", line 3, in <module>
    import signatures.checks
  File "/Users/d0nest/Stuff/Tools/dnsReaper/signatures/checks/__init__.py", line 9, in <module>
    from . import *
  File "/Users/d0nest/Stuff/Tools/dnsReaper/signatures/checks/WEB.py", line 1, in <module>
    from domain import Domain
  File "/Users/d0nest/Stuff/Tools/dnsReaper/domain.py", line 14, in <module>
    import whois
ModuleNotFoundError: No module named 'whois'
```

**Comment by SimonGurney** [comment]
Hi,

We use python-whois, not whois.

You are better off installing the requirements with the requirements.txt file which also specifics the right versions.

https://github.com/punk-security/dnsReaper/blob/main/requirements.txt

Something like
pip install -r requirements.txt

**Comment by d0nest** [comment]
Thanks a lot sir! The issue was on my side, it was due to different versions of pip.
