### ISSUE TITLE
GoDaddy Provider Domain Not Found Error

### ISSUE THREAD

**Issue by wf-aw** [punk-security/dnsReaper#182]
I'm getting a "domain not found" error for a domain that we purchased through Godaddy but the records are being hosted elsewhere (the only records in Godaddy are NS records). I'm assuming this will happen for any other domains like this but it didn't get to that point after erroring out.

`Traceback (most recent call last):\n  File "/var/task/./dnsReaper/main.py", line 149, in <module>\n    asyncio.run(main())\n  File "/var/lang/lib/python3.11/asyncio/runners.py", line 190, in run\n    return runner.run(main)\n           ^^^^^^^^^^^^^^^^\n  File "/var/lang/lib/python3.11/asyncio/runners.py", line 118, in run\n    return self._loop.run_until_complete(task)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/var/lang/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File "/var/task/./dnsReaper/main.py", line 104, in main\n    domains = list(provider.fetch_domains(**args.__dict__))\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/var/task/dnsReaper/providers/godaddy.py", line 104, in fetch_domains\n    records = api.get_records(domain).json()\n              ^^^^^^^^^^^^^^^^^^^^^^^\n  File "/var/task/dnsReaper/providers/godaddy.py", line 49, in get_records\n    raise DomainNotFoundError(domain)\nproviders.godaddy.DomainNotFoundError: Domain not found: <redacted>.net\n')`

**Comment by SimonGurney** [comment]
So the error is caused because you have a domain in GoDaddy but it's configured for dns hosting elsewhere and GoDaddy just points NS records to that other provider?

**Comment by SimonGurney** [comment]
If so, we'll try to reproduce and handle this better.

For now, you can manually list the domains you want to ingest (comma separated) with --gd-domains

**Comment by wf-aw** [comment]
> So the error is caused because you have a domain in GoDaddy but it's configured for dns hosting elsewhere and GoDaddy just points NS records to that other provider?

Yes this is correct. And ok thank you, I'll do that for now!
